name: Add Issue or PR to a Core Contributor project board
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      board_name:
        required: true
        type: string
      item_url:
        required: true
        type: string
    secrets:
      projects_access_token:
        required: true

jobs:
  add-item:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Map board name to board URL
        run: |
          case "${{ inputs.board_name }}" in
            cc-edx-platform)
              echo "PROJECT_NUMBER=1" >> $GITHUB_ENV
              ;;
            cc-frontend-apps)
              echo "PROJECT_NUMBER=2" >> $GITHUB_ENV
              ;;
            cc-core-apps)
              echo "PROJECT_NUMBER=3" >> $GITHUB_ENV
              ;;
            cc-other-utils)
              echo "PROJECT_NUMBER=4" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown board name: '${{ inputs.board_name }}'" >&2
              exit 1
              ;;
          esac

      - name: Add item to board
        run: |
          gh project list --owner ChrisChV-Sandbox-Organization
          gh project item-add ${{ env.PROJECT_NUMBER }} --owner ChrisChV-Sandbox-Organization --url ${{ inputs.item_url }}
        env:
          GH_TOKEN: ${{ secrets.projects_access_token }}
