name: Add Issue or PR to a Core Contributor project board
on:
  workflow_call:
    inputs:
      item_number:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      board_name:
        required: true
        type: string
      item_type:
        required: true
        type: string  # "issue" or "pull_request"

jobs:
  add-item:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Map board name to board URL
        run: |
          case "${{ inputs.board_name }}" in
            cc-edx-platform)
              echo "PROJECT_URL=https://github.com/orgs/openedx/projects/1" >> $GITHUB_ENV
              ;;
            cc-frontend-apps)
              echo "PROJECT_URL=https://github.com/orgs/openedx/projects/2" >> $GITHUB_ENV
              ;;
            cc-core-apps)
              echo "PROJECT_URL=https://github.com/orgs/openedx/projects/3" >> $GITHUB_ENV
              ;;
            cc-other-utils)
              echo "PROJECT_URL=https://github.com/orgs/openedx/projects/4" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown board name: '${{ inputs.board_name }}'" >&2
              exit 1
              ;;
          esac

      - name: Get Content ID (Issue o PR)
        run: |
          ITEM_TYPE="${{ inputs.item_type }}"
          ITEM_NUMBER="${{ inputs.item_number }}"
          REPO_NAME="${{ inputs.repo_name }}"

          if ! CONTENT_ID=$(gh "$ITEM_TYPE" view "$ITEM_NUMBER" --repo "$REPO_NAME" --json id --jq '.id'); then
            echo "Failed to fetch content ID"
            exit 1
          fi

          echo "CONTENT_ID=$CONTENT_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add item to board
        run: |
          gh project item-add ${{ env.PROJECT_URL }} --owner openedx --content-id ${{ env.CONTENT_ID }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
